Fix compilation errors in index.js
`index.js` currently re-exports the `default` export from several packages
as its own. However, every JS module can only have at most a single
`default` export. This was giving rise to errors like:

ERROR in ../stripes-components/index.js
Module build failed: SyntaxError: Only one default export allowed per module. (3:8)

  1 | /*form elements*/
  2 | export {default} from './lib/Button';
> 3 | export {default} from './lib/Checkbox';
    |         ^

This change re-exports each referenced component module as a named
export so that you can import them by name. E.g.

```js
import { Button } from '@folio/stripes-components';
```

> Note: `InputList` does not appear to be in the codebase anymore, so
> that export was removed.